package net.pilseong.todocompose.util

enum class Action {
    ADD,
    UPDATE,
    DELETE,
    DELETE_ALL,
    UNDO,
    PRIORITY_CHANGE,
    SORT_ORDER_CHANGE,
    SORT_DATE_CHANGE,
    SEARCH_WITH_DATE_RANGE,
    SORT_FAVORITE_CHANGE,
    FAVORITE_UPDATE,
    NOTEBOOK_CHANGE,
    DELETE_SELECTED_ITEMS,
    MOVE_TO,
    STATE_FILTER_CHANGE,
    STATE_CHANGE,
    STATE_CHANGE_MULTIPLE,
    SEARCH_RANGE_CHANGE,
    PRIORITY_FILTER_CHANGE,
    NO_ACTION
}