package net.pilseong.todocompose.ui.screen.list

enum class MemoAction {
    ADD,
    UPDATE,
    DELETE,
    DELETE_ALL,
    UNDO,
    PRIORITY_CHANGE,
    SORT_ORDER_CHANGE,
    SEARCH_WITH_DATE_RANGE,
    SORT_FAVORITE_CHANGE,
    FAVORITE_UPDATE,
    NOTEBOOK_CHANGE,
    DELETE_SELECTED_ITEMS,
    MOVE_TO,
    COPY_TO,
    STATE_FILTER_CHANGE,
    STATE_MULTIPLE_FILTER_CHANGE,
    STATE_CHANGE,
    STATE_CHANGE_MULTIPLE,
    STATUS_LINE_UPDATE,
    SEARCH_RANGE_CHANGE,
    SEARCH_NO_FILTER_CHANGE,
    PRIORITY_FILTER_CHANGE,
    NO_ACTION,
    MEMO_SORT_DATE_BASE_CHANGE
}